[package]
name = "twentythreeraindrops"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "23raindrops"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dasp = "0.11.0"
glium = "*"